### ISSUE TITLE
created_at, elapsed_at, finished_at

### ISSUE THREAD

**Issue by chrzrdx** [Shinu007/Website_Word_counter#3]
All jobs show that they have elapsed_at nearly at the same time as they've been created_at. What is elapsed_at exactly?

Also, finished_at values are 5 hours 30 minutes more than the created_at values. The jobs couldn't have run for this long. Can you see what's going on here?

**Comment by dxter6** [comment]
Working it is due to UTC and IST time zones

**Comment by chrzrdx** [comment]
What does elapsed_at mean?
